# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  typescript = nodeEnv.buildNodePackage {
    name = "typescript";
    packageName = "typescript";
    version = "2.3.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript/-/typescript-2.3.3.tgz";
      sha1 = "9639f3c3b40148e8ca97fe08a51dd1891bb6be22";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript is a language for application scale JavaScript development";
      homepage = http://typescriptlang.org/;
      license = "Apache-2.0";
    };
    production = true;
  };
}